apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
data:
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  CART_HOST: "cart"
  CART_PORT: "8080"
  SHIPPING_HOST: "shipping"
  SHIPPING_PORT: "8080"
  PAYMENT_HOST: "payment"
  PAYMENT_PORT: "8080"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    project: roboshop
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: frontend
  template:
    metadata:
      labels:
        project: roboshop
        app: frontend
    spec:
      containers:
        - name: frontend
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
          envFrom:
            - configMapRef:
                name: frontend



